---

- name: copy over z-wave installation script
  copy: src=razberry-install dest=/opt/razberry-install mode=0755

- name: create z-way configuration directory
  file: path=/etc/z-way state=directory mode=0755

- name: mark the installation questions as already answered
  file: path=/etc/z-way/box_type state=touch

- name: disable serial console in cmdline.txt
  replace: dest=/boot/cmdline.txt regexp='console=serial0,115200'

- name: disable serial console on ttyAMA0 which is used by Razberry
  service: name=serial-getty@ttyAMA0 enabled=no state=stopped
  notify: restart z-way

- name: install z-way server
  shell: bash /opt/razberry-install | tee razberry-install.log
  args:
    creates: /etc/z-way/VERSION
    chdir: /tmp

